### ISSUE TITLE
Fusion, Face , HD Face

### ISSUE THREAD

**Issue by iblazhev** [joshuajnoble/ofxKinectV2#5]
Hey,
I have some questions.
- Do we have the Fusion, Face, HD Face in the ofxKinectV2?
- What's the difference between that project and ofxKinectCommonBridge v2  - https://github.com/joshuajnoble/ofxKinectCommonBridge/tree/kcbv2?

Regards,
Ivaylo

**Comment by joshuajnoble** [comment]
> What's the difference between that project and ofxKinectCommonBridge v2 - https://github.com/joshuajnoble/ofxKinectCommonBridge/tree/kcbv2?

This is for the Kinect V2 and the https://github.com/joshuajnoble/ofxKinectCommonBridge/tree/kcbv2 was for testing a second release of Kinect Common Bridge for Kinect v1. Bad naming on my part.

> Do we have the Fusion, Face, HD Face in the ofxKinectV2?

No. This is essentially a wrapper of the KinectCommonBridge for Kinect V2 created my Microsoft Open Tech an open source compatibility group within MS. If they aren't supporting it, this doesn't, though from experience I can say that it's not too hard to add it into this.
