### ISSUE TITLE
Hot to show the RGB camera view

### ISSUE THREAD

**Issue by micrem73** [joshuajnoble/ofxKinectV2#6]
simply, i think would be enough to change the line
  kinect.drawDepth(0, 0);
in
  kinect.draw(0, 0);

but this doesn't show anything.
What am I doing wrong?

**Comment by obviousjim** [comment]
try disabling alpha blending...?

On Mon, Sep 1, 2014 at 10:37 AM, micrem73 notifications@github.com wrote:

> simply, i think would be enough to change the line
> kinect.drawDepth(0, 0);
> in
> kinect.draw(0, 0);
> 
> but this doesn't show anything.
> What am I doing wrong?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/joshuajnoble/ofxKinectV2/issues/6.

## 
- James

**Comment by micrem73** [comment]
I just modified the example program; there alpha blending is disabled in setup function, with the call ofDisableAlphaBlending();

**Comment by micrem73** [comment]
I noticed that in original ofxKinectCommonbridge addon, the example call the init function with three parameters
    kinect.initColorStream(640, 480, true);

and in the example-simple of ofxKinectv2, it's called instead this way:
    kinect.initColorStream(true);

If i put all three params, build fails - Error  3   error C2660: 'ofxKinectCommonBridge::initColorStream' : function does not take 3 arguments  c:\users\michelecremaschi\documents\of_v0.8.3_vs_release\addons\ofxkinectv2\example-simple\src\testapp.cpp  8   1   example-Simple

Does this help?

**Comment by micrem73** [comment]
I succeeded showing the RGB image using @quinkennedy fork
