### ISSUE TITLE
Adding a KCBGetDepthCameraIntrinsics method in KCBv2Lib.h

### ISSUE THREAD

**Issue by frankiezafe** [joshuajnoble/ofxKinectV2#9]
Hello, i'd like to add a method to retrieve the camera intrinsics values.
An interface is available in Kinect.h (line 7639, virtual HRESULT STDMETHODCALLTYPE GetDepthCameraIntrinsics), but i can't find the source of the dll you use in the repo...
Could you help me?

**Comment by joshuajnoble** [comment]
It's here: https://github.com/msopentech/KinectCommonBridge

**Comment by frankiezafe** [comment]
thanks! i'll check this soon and let u know :)
